trigger:
  branches:
    include:
      - main
  paths:
    include:
      - cicd/*
    exclude:
      - azure/*
 
pool:
  vmImage: windows-latest
 
stages:
  - template: ./build.yaml
    parameters:
      library: 'Blazor Dev'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Dev'
      stage: 'Build'
      service_connection: 'tlie-sc'

  - template: ./deploy.yaml
    parameters:
      library: 'Blazor Dev'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Dev'
      stage: 'Dev'
      service_connection: 'tlie-sc'

  - template: ./deploy.yaml
    parameters:
      library: 'Blazor Qa'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Qa'
      stage: 'Qa'
      service_connection: 'tlie-sc'

  - template: ./deploy.yaml
    parameters:
      library: 'Blazor Prod'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Prod'
      stage: 'Prod'
      service_connection: 'tlie-sc'

      