trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure/*
 
pool:
  vmImage: ubuntu-latest # or windows-latest
 
stages:
  - template: ./deploy-shared.yaml
    parameters:
      library: 'Blazor Shared'
      environment: 'Blazor Shared'
      stage: 'Shared'
      service_connection: tlie-sc'

  - template: ./deploy-infra.yaml
    parameters:
      library: 'Blazor Dev'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Dev'
      stage: 'Dev'
      service_connection: tlie-sc'

  - template: ./deploy-infra.yaml
    parameters:
      library: 'Blazor Qa'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Qa'
      stage: 'Qa'
      service_connection: tlie-sc'

  - template: ./deploy-infra.yaml
    parameters:
      library: 'Blazor Prod'
      library_shared: 'Blazor Shared'
      environment: 'Blazor Prod'
      stage: 'Prod'
      service_connection: tlie-sc'

      