parameters:
  library: ''
  library_shared: ''
  environment: ''
  service_connection: ''
  stage: ''

stages:
  - stage: ${{ parameters.stage }}
    dependsOn: Shared
    variables:
    - group: ${{ parameters.library }}
    - group: ${{ parameters.library_shared }}
    displayName: Infrastructure ${{ parameters.stage }}
    jobs:
      - deployment: Approval
        environment: ${{ parameters.environment }}
      - job: deploy
        steps:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens'
            enabled: true
            inputs:
              rootDirectory: './azure'
              targetFiles: |
               **/*.json
              escapeType: none
              keepToken: true

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Validate Template'
            enabled: true
            inputs:
              ConnectedServiceName: '${{ parameters.service_connection }}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resource_group_name)'
              location: '$(location)'
              csmFile: './azure/template.json'
              csmParametersFile: './azure/parameters.json'
              deploymentMode: Validation
              deploymentName: '${{ parameters.stage }}'
              addSpnToEnvironment: true
                 
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy ARM Template'
            enabled: true
            inputs:
              ConnectedServiceName: '${{ parameters.service_connection }}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(resource_group_name)'
              location: '$(location)'
              csmFile: './azure/template.json'
              csmParametersFile: './azure/parameters.json'
              deploymentMode: Incremental
              deploymentName: '${{ parameters.stage }}'
              addSpnToEnvironment: true